export default {
	LOGIN 	                        : 'LOGIN',
	STORE_PROFILE 	                : 'STORE_PROFILE',
	UPDATE_USER 				    : 'UPDATE_USER',
    STORE_WOO_PRODUCTS 			    : 'STORE_WOO_PRODUCTS',
    STORE_WOO_CATEGORIES 			: 'STORE_WOO_CATEGORIES',
    STORE_WOO_TAGS 					: 'STORE_WOO_TAGS',
    CLEAR_STORE_WOO_PRODUCTS 		: 'CLEAR_STORE_WOO_PRODUCTS',
	STORE_CHECKED_PRODUCTS 		    : 'STORE_CHECKED_PRODUCTS',
	EDIT_WOO_PRODUCT  			    : 'EDIT_WOO_PRODUCT',
	UPDATE_WOO_PRODUCT  			: 'UPDATE_WOO_PRODUCT',
	DELETE_WOO_PRODUCT  			: 'DELETE_WOO_PRODUCT',
	LOADING  			            : 'LOADING',
	LOGOUT  			            : 'LOGOUT'
};